version: '3.3'

services:
  postgres-nest:
    image: postgres:alpine
    ports: 
      - '5432:5432'
    container_name: 'pgsql-nest'
    restart: always
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: pgnest
      POSTGRES_PASSWORD: pgnest123

volumes:
  pg-data:

